In [10]:
import numpy as np

In [13]:
#Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
#Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
a = np.random.randint(1, 11, size=(5,5))
a

array([[ 9,  7, 10,  3,  5],
       [10,  8,  1,  8,  1],
       [10,  7,  8,  8, 10],
       [10, 10,  7,  9,  6],
       [ 5,  8,  8, 10,  4]])

In [27]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a = np.random.rand(4,4)
a

array([[0.05766408, 0.38626131, 0.36150373, 0.08091896],
       [0.71996631, 0.44475991, 0.54372155, 0.41303248],
       [0.51649013, 0.19690525, 0.43102178, 0.46117858],
       [0.18217132, 0.57320282, 0.0697568 , 0.80223689]])

In [35]:
#Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[ 4  7  9  9 10]
[ 1  4  6 10  4]
[ 5 11 15 19 14]
[ 3  3  3 -1  6]
[ 4 28 54 90 40]


In [38]:
#Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a, b))

[0.60037289 0.99733968 0.44088789 0.74795632 0.63109427 0.14117807
 0.80159757]
[0.64549417 0.75851054 0.70507306 0.30967834 0.7448448  0.47551861
 0.76986331]
2.8408345451342907


In [39]:
#Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,3))
print(a)
print(b)
print(np.dot(a, b))

[[7 4]
 [6 2]]
[[ 2  6 10]
 [10  3  5]]
[[54 54 90]
 [32 42 70]]


In [40]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(1, 11, size=(3,3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 1  3  6]
 [ 4  2 10]
 [ 5  8  8]]
[[-0.52459016  0.19672131  0.14754098]
 [ 0.14754098 -0.18032787  0.1147541 ]
 [ 0.18032787  0.05737705 -0.08196721]]


In [41]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.rand(4,4)
print(a)
b = a.T
print(b)

[[0.47225142 0.75686834 0.9780289  0.47881872]
 [0.27461743 0.84022096 0.32816196 0.51842771]
 [0.22750658 0.18802934 0.76640104 0.99261972]
 [0.71119034 0.90822256 0.97445997 0.52070653]]
[[0.47225142 0.27461743 0.22750658 0.71119034]
 [0.75686834 0.84022096 0.18802934 0.90822256]
 [0.9780289  0.32816196 0.76640104 0.97445997]
 [0.47881872 0.51842771 0.99261972 0.52070653]]


In [42]:
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, 4)
print(a)
print(b)
print(np.dot(a, b))

[[ 4 10  7  6]
 [10  8  6  6]
 [ 4  2  9  7]]
[2 5 8 3]
[132 126 111]


In [43]:
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.rand(2,3)
b = np.random.rand(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.5644015  0.46374098 0.32224033]
 [0.2641319  0.79279668 0.7441488 ]]
[0.21673183 0.93251526 0.1879531 ]
[0.61533538 0.93640586]


In [44]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))
print(a)
print(b)
print(a*b)

[[1 1]
 [2 5]]
[[6 5]
 [9 5]]
[[ 6  5]
 [18 25]]


In [45]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))
print(a)
print(b)
c = np.dot(a, b)
print(c)

[[4 4]
 [9 2]]
[[ 2  4]
 [10  6]]
[[48 40]
 [38 48]]


In [46]:
#Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(1, 101, size=(5,5))
print(a)
print(a.sum())

[[71 59 75  9 84]
 [ 6 80 57 90 19]
 [ 8 93 99 51 87]
 [52 41 35 39 25]
 [21 57 71 68 69]]
1366


In [47]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a = np.random.randint(1, 11, size=(4,4))
b = np.random.randint(1, 11, size=(4,4))
print(a)
print(b)
print(a-b)

[[ 5  4  5  2]
 [ 6  5  4  5]
 [ 6  9  6  5]
 [10  8  7  1]]
[[ 1  1  3  5]
 [ 1  2  7  9]
 [10  2  5  9]
 [ 6  4  8  2]]
[[ 4  3  2 -3]
 [ 5  3 -3 -4]
 [-4  7  1 -4]
 [ 4  4 -1 -1]]


In [48]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a = np.random.rand(3,3)
print(a)

[[0.81929354 0.40973615 0.10384335]
 [0.9120332  0.34828236 0.33224677]
 [0.09312959 0.35183783 0.37716866]]


In [55]:
#Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a = [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
print(a)

squared_matrix = np.square(a)
print(squared_matrix)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [56]:
#Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.random.randint(1, 51, size=(4))
print(a)

squared_vector = np.square(a)
print(squared_vector)

[27  5 34  8]
[ 729   25 1156   64]
